services:

  config-service:
    image: riserdark/paas/house-config:latest
    container_name: config_service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/house_config
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
    depends_on:
      - queuing-service
      - postgres
    ports:
      - "8085:8085"
    networks:
      - paas-shared-network

  notification-service:
    image: riserdark/paas/notification-service:latest
    container_name: notification_service
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - redis
    ports:
      - "8083:8083"
    networks:
      - paas-shared-network

networks:
  paas-shared-network:
    driver: overlay