services:
  frontend:
    image: riserdark/paas:house-front
    container_name: house_front
    ports:
      - "8080:80"
    volumes:
      - nginx.conf:/etc/nginx/nginx.conf
    networks:
      - paas-shared-network

networks:
  paas-shared-network:
    driver: overlay
    external: true