services:
  iot-service:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ../IotService/config:/mosquitto/config
      - ../IotService/data:/mosquitto/data
      - ../IotService/log:/mosquitto/log
    environment:
      - MOSQUITTO_PASSWORD_FILE=/mosquitto/config/pwfile
    networks:
      - paas-shared-network

  queuing-service:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    volumes:
      - ../QueuingService/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ../QueuingService/definitions.json:/etc/rabbitmq/definitions.json
    environment:
      - RABBITMQ_DEFAULT_USER=ing3
      - RABBITMQ_DEFAULT_PASS=paas
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
      - RABBITMQ_DEFINITIONS_FILE=/etc/rabbitmq/definitions.json
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - paas-shared-network

  notification-manager:
    image: riserdark/paas/notification-manager:latest
    container_name: notification_manager
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_LOG_QUEUE: log_queue
      RABBITMQ_LOG_EXCHANGE: log_exchange
      RABBITMQ_LOG_KEY: log_routing_key
      RABBITMQ_USER: ing3
      RABBITMQ_PASS: paas
      REDIS_HOST: redis
      REDIS_PORT: 6379
      POSTGRES_HOST: postgres
      POSTGRES_DB: house_config
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_PORT: 5432
    depends_on:
      - queuing-service
      - redis
      - postgres
    command: [ "poetry", "run", "python", "main.py" ]
    networks:
      - paas-shared-network

  data-exchange:
    image: riserdark/paas/data-exchange:latest
    container_name: data_exchange
    environment:
      MQTT_BROKER: mosquitto
      MQTT_PORT: 1883
      MQTT_CONS_TOPIC: mqtt/log-topic
      MQTT_PROD_TOPIC: mqtt/config-topic
      MQTT_USER: exchange
      MQTT_PASS: toto
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_CONF_EXCHANGE: config_exchange
      RABBITMQ_CONF_QUEUE: config_queue
      RABBITMQ_CONF_KEY: config_routing_key
      RABBITMQ_LOG_EXCHANGE: log_exchange
      RABBITMQ_LOG_QUEUE: log_queue
      RABBITMQ_LOG_KEY: log_routing_key
      RABBITMQ_USER: ing3
      RABBITMQ_PASS: paas
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      POSTGRES_HOST: postgres
      POSTGRES_DB: house_config
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_PORT: 5432
    depends_on:
      - queuing-service
      - iot-service
      - mongodb
      - postgres
    command: [ "poetry", "run", "python", "main.py" ]
    networks:
      - paas-shared-network

networks:
  paas-shared-network:
    driver: overlay
    external: true